"""Add profile_suggestions table

Revision ID: 3698a4d10bc8
Revises: d4508c1fe4e3
Create Date: 2025-12-08 19:33:34.196796

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "3698a4d10bc8"
down_revision: Union[str, Sequence[str], None] = "d4508c1fe4e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
